cod_behavior:
  ros__parameters:
    nav_pose:
      home:
        frame_id: "map"
        position:
          x: 0.0
          y: 0.0
          z: 0.0
        orientation:
          w: 1.0

      main:
        frame_id: "map"
        position:
          x: 2.0
          y: 0.0
          z: 0.0
        orientation:
          w: 1.0

    patrol_pose:
      first:
        frame_id: "map"
        position:
          x: 2.0
          y: 1.0
          z: 0.0
        orientation:
          w: 1.0

      second:
        frame_id: "map"
        position:
          x: -2.0
          y: 1.0
          z: 0.0
        orientation:
          w: 1.0

      third:
        frame_id: "map"
        position:
          x: -2.0
          y: 1.0
          z: 0.0
        orientation:
          w: 1.0